# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project_info: 
  project_number: "24-08420-000" # USE PROJ # FROM ESDAT
  project_name:   "Box of Rain" # USE PROJ ESDAT PROJ NAME
  #project_site:   "Park-Place" # PROJECT SITE IN ESDAT
  