# Information for configurating script and converting EDDs

# Please enter all necessary information below before running scripts


project_info: 
  project_number: "23-08229-000" # USE PROJ # FROM ESDAT
  project_name:   "PBOOM: Park Place" # USE PROJ ESDAT PROJ NAME
  project_site:   "Park-Place" # PROJECT SITE IN ESDAT
  